# fly.toml app configuration file generated for storybot-fragrant-paper-6245 on 2025-05-02T23:45:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'storybot-fragrant-paper-6245'
primary_region = 'sjc'

[env]
  PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"

[processes]
  app = "python instagram_monitor.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

